spring:
  application:
    name: rate_my_first_line

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5447/rate_my_first_line
    username: rate_my_first_line
    password: rate_my_first_line11

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
<<<<<<< Updated upstream
    locations: classpath:db/migration
    baseline-on-migrate: true

=======
    locations: classpath:db/migration
>>>>>>> Stashed changes
